export const BLOCKCHAIN__SET_LOADING = '[BLOCKCHAIN] SET_LOADING';
export const BLOCKCHAIN__SET_ACCOUNT = '[BLOCKCHAIN] SET_ACCOUNT';
export const BLOCKCHAIN__FETCH = '[BLOCKCHAIN] FETCH';
export const BLOCKCHAIN__SET_WEB3MODAL = '[BLOCKCHAIN] SET_WEB3MODAL';
