export const BLOCKCHAIN__SET_LOADING = '[BLOCKCHAIN] SET_LOADING';
export const BLOCKCHAIN__SET_ACCOUNT = '[BLOCKCHAIN] SET_ACCOUNT';
export const BLOCKCHAIN__FETCH = '[BLOCKCHAIN] FETCH';
export const BLOCKCHAIN__SET_WEB3MODAL = '[BLOCKCHAIN] SET_WEB3MODAL';
export const BLOCKCHAIN__SET_PROVIDER = '[BLOCKCHAIN] SET_PROVIDER';
export const BLOCKCHAIN__DISCONNECT = '[BLOCKCHAIN] DISCONNECT';
export const BLOCKCHAIN__UPDATE_ACCOUNT_ASYNC = '[BLOCKCHAIN] UPDATE_ACCOUNT_ASYNC';
