export const BLOCKCHAIN__SET_LOADING = '[BLOCKCHAIN] SET_LOADING';
export const BLOCKCHAIN__SET_ACCOUNT = '[BLOCKCHAIN] SET_ACCOUNT';
export const BLOCKCHAIN__FETCH = '[BLOCKCHAIN] FETCH';
export const BLOCKCHAIN__SET_WEB3MODAL = '[BLOCKCHAIN] SET_WEB3MODAL';
export const BLOCKCHAIN__SET_PROVIDER = '[BLOCKCHAIN] SET_PROVIDER';
export const BLOCKCHAIN__DISCONNECT = '[BLOCKCHAIN] DISCONNECT';
export const BLOCKCHAIN__UPDATE_ACCOUNT_ASYNC = '[BLOCKCHAIN] UPDATE_ACCOUNT_ASYNC';
export const BLOCKCHAIN__SET_IS_CONNECTED = '[BLOCKCHAIN] SET_IS_CONNECTED';

export const APP__SET_IS_SCROLL = '[APP] SET_IS_SCROLL';
export const APP__SET_WIDTH = '[APP] SET_WIDTH';
export const APP__SET_SLIDER_NEXT = '[APP] SET_SLIDER_NEXT';
export const APP__SET_SLIDER_PREV = '[APP] SET_SLIDER_PREV';
export const APP__SET_SLIDER_SLIDING = '[APP] SET_SLIDER_SLIDING';
export const APP__SET_SLIDER_DIR = '[APP] SET_SLIDER_DIR';
